import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        bg: "var(--bg)",
        "bg-secondary": "var(--bg-secondary)",
        "bg-tertiary": "var(--bg-tertiary)",
        "bg-elevated": "var(--bg-elevated)",
        card: "var(--card)",
        "card-elevated": "var(--card-elevated)",
        "card-border": "var(--card-border)",
        "card-border-light": "var(--card-border-light)",
        "card-highlight": "var(--card-highlight)",
        primary: "var(--primary)",
        success: "var(--success)",
        destructive: "var(--destructive)",
        warning: "var(--warning)",
        accent: "var(--accent)",
        teal: "var(--teal)",
        purple: "var(--purple)",
        pink: "var(--pink)",
        indigo: "var(--indigo)",
        fg: "var(--fg)",
        "fg-secondary": "var(--fg-secondary)",
        "fg-tertiary": "var(--fg-tertiary)",
        "fg-quaternary": "var(--fg-quaternary)",
        muted: "var(--muted)",
        border: "var(--border)",
        separator: "var(--separator)",
        "separator-subtle": "var(--separator-subtle)",
        "separator-opaque": "var(--separator-opaque)",
        fill: "var(--fill)",
        "fill-secondary": "var(--fill-secondary)",
        "fill-tertiary": "var(--fill-tertiary)",
        "fill-quaternary": "var(--fill-quaternary)",
        "on-primary": "var(--on-primary)",
        "on-success": "var(--on-success)",
        "on-destructive": "var(--on-destructive)",
        "on-accent": "var(--on-accent)",
        secondary: "var(--secondary)",
        flame: "var(--flame)",
        "flame-mid": "var(--flame-mid)",
        "flame-secondary": "var(--flame-secondary)",
        // Alphas
        "primary-alpha-08": "var(--primary-alpha-08)",
        "primary-alpha-12": "var(--primary-alpha-12)",
        "primary-alpha-16": "var(--primary-alpha-16)",
        "primary-alpha-20": "var(--primary-alpha-20)",
        "primary-alpha-30": "var(--primary-alpha-30)",
        "success-alpha-12": "var(--success-alpha-12)",
        "success-alpha-20": "var(--success-alpha-20)",
        "success-alpha-30": "var(--success-alpha-30)",
        "destructive-alpha-12": "var(--destructive-alpha-12)",
        "destructive-alpha-20": "var(--destructive-alpha-20)",
        "warning-alpha-20": "var(--warning-alpha-20)",
        "warning-alpha-30": "var(--warning-alpha-30)",
        "accent-alpha-12": "var(--accent-alpha-12)",
        "accent-alpha-20": "var(--accent-alpha-20)",
        "teal-alpha-20": "var(--teal-alpha-20)",
        "purple-alpha-12": "var(--purple-alpha-12)",
        "purple-alpha-16": "var(--purple-alpha-16)",
        "flame-alpha-10": "var(--flame-alpha-10)",
        "flame-alpha-20": "var(--flame-alpha-20)",
        "flame-alpha-25": "var(--flame-alpha-25)",
        // Charts
        "chart-1": "var(--chart-1)",
        "chart-2": "var(--chart-2)",
        "chart-3": "var(--chart-3)",
        "chart-4": "var(--chart-4)",
        "chart-5": "var(--chart-5)",
        // Day badges
        "day-mon": "var(--day-mon)",
        "day-tue": "var(--day-tue)",
        "day-wed": "var(--day-wed)",
        "day-thu": "var(--day-thu)",
        "day-fri": "var(--day-fri)",
        "day-sat": "var(--day-sat)",
        "day-sun": "var(--day-sun)",
        // Heatmap
        "heatmap-0": "var(--heatmap-0)",
        "heatmap-1": "var(--heatmap-1)",
        "heatmap-2": "var(--heatmap-2)",
        "heatmap-3": "var(--heatmap-3)",
        "heatmap-4": "var(--heatmap-4)",
        // Sidebar
        "sidebar-bg": "var(--sidebar-bg)",
        "sidebar-border": "var(--sidebar-border)",
        "sidebar-item-hover": "var(--sidebar-item-hover)",
        "sidebar-item-active": "var(--sidebar-item-active)",
        // Overlays
        "overlay-subtle": "var(--overlay-subtle)",
        "overlay-medium": "var(--overlay-medium)",
        "overlay-heavy": "var(--overlay-heavy)",
      },
      borderRadius: {
        xs: "6px",
        sm: "10px",
        md: "13px",
        lg: "16px",
        xl: "22px",
        "2xl": "20px",
        "3xl": "24px",
        pill: "9999px",
      },
      spacing: {
        xxs: "2px",
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        xxl: "24px",
        xxxl: "32px",
        "4xl": "48px",
        "5xl": "64px",
      },
      fontSize: {
        xxs: ["10px", { lineHeight: "14px" }],
        xs: ["11px", { lineHeight: "15px" }],
        sm: ["12px", { lineHeight: "16px" }],
        md: ["13px", { lineHeight: "18px" }],
        base: ["14px", { lineHeight: "20px" }],
        lg: ["16px", { lineHeight: "22px" }],
        xl: ["18px", { lineHeight: "24px" }],
        xxl: ["24px", { lineHeight: "30px" }],
        display: ["28px", { lineHeight: "34px" }],
      },
      fontWeight: {
        regular: "400",
        medium: "500",
        semibold: "600",
        bold: "700",
        extrabold: "800",
        black: "900",
      },
      boxShadow: {
        subtle: "var(--shadow-subtle)",
        card: "var(--shadow-card)",
        elevated: "var(--shadow-elevated)",
        modal: "var(--shadow-modal)",
      },
    },
  },
  plugins: [],
};

export default config;
